### ISSUE TITLE
Bug in app.y: Product.Product... instead of Product...

### ISSUE THREAD

**Issue by r-owen** [RobertLuptonTheGood/eups#66]
Line 719 of app.y includes: `Product.Product.LocalVersionPrefix` which fails with `setup: type object 'Product' has no attribute 'Product'`.

I think the best fix is to change the import statement `from . import Product` to `from .Product import Product` and change `Product.Product` to `Product`. The former is optional but makes the intent much clearer.

Also, this file has 16 pyflakes linter warnings, including some undefined names that likely indicate errors and many packages that are imported but not used.

**Comment by timj** [comment]
I am guessing this broke in d3d0afa200ca22809ae7be7eda0b19a9d81ded6c (as part of #52). @migueldvb?

**Comment by r-owen** [comment]
I have a branch with a fix and also fixes for some other bugs found by pyflakes. I'm just waiting permission to commit it. However, I can provide it some other way if preferred.

**Comment by migueldvb** [comment]
Changing from . import Product to from .Product import looks like the best solution. This import should work with python 2 and 3.

**Comment by timj** [comment]
@r-owen can you just do a pull request like @migueldvb does? I can merge the PR.
